// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileNameByFilePath(arg1) {
  return window['go']['main']['App']['GetFileNameByFilePath'](arg1);
}

export function GetStorage(arg1) {
  return window['go']['main']['App']['GetStorage'](arg1);
}

export function Query(arg1, arg2, arg3) {
  return window['go']['main']['App']['Query'](arg1, arg2, arg3);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SaveStorage(arg1, arg2) {
  return window['go']['main']['App']['SaveStorage'](arg1, arg2);
}

export function TestConnect(arg1, arg2) {
  return window['go']['main']['App']['TestConnect'](arg1, arg2);
}
